version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: backend
    working_dir: /backend
    volumes:
      - ./app:/backend/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./files:/usr/share/nginx/html/files
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  files:
