"""Initial migration with pgvector support

Revision ID: ffe29ac54f8c
Revises: 
Create Date: 2025-08-24 02:20:04.185881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe29ac54f8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diary_vector_diary_id_fkey'), 'diary_vector', type_='foreignkey')
    op.create_foreign_key(None, 'diary_vector', 'diary', ['diary_id'], ['diary_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diary_vector', type_='foreignkey')
    op.create_foreign_key(op.f('diary_vector_diary_id_fkey'), 'diary_vector', 'diary', ['diary_id'], ['diary_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    
    # Note: pgvector extension is not dropped to avoid data loss
    # If you really need to drop it, uncomment the following line:
    # op.execute('DROP EXTENSION IF EXISTS vector CASCADE')
